language: rust
rust:
  - nightly
  - beta
  - stable
after_success:
  - |
        test ${TRAVIS_PULL_REQUEST} == "false" && \
        test ${TRAVIS_BRANCH} == "master" && \
        test "${TRAVIS_BUILD_NUMBER}.3" == "${TRAVIS_JOB_NUMBER}" && \
        bash deploy-docs.sh
